# coding: utf-8
namespace :byod_cloud do
  desc "Init action names"
  task init_action_names: :environment do

    action_names = [
      # 安全
      { id: 1, action_name: 'index', controller_name: 'enterprise', is_nav_link: true },
      { id: 2, action_name: 'index', controller_name: 'enterprise/rule_templates', is_nav_link: true },
      { id: 3, action_name: 'create', controller_name: 'enterprise/rule_templates' },
      { id: 4, action_name: 'show', controller_name: 'enterprise/rule_templates' },
      { id: 5, action_name: 'update', controller_name: 'enterprise/rule_templates' },
      { id: 6, action_name: 'destroy', controller_name: 'enterprise/rule_templates' },
      { id: 7, action_name: 'index', controller_name: 'enterprise/admin_users', is_nav_link: true },
      { id: 8, action_name: 'create', controller_name: 'enterprise/admin_users/roles' },
      { id: 9, action_name: 'render_global_setting_json', controller_name: 'enterprise/global_settings' },
      { id: 10, action_name: 'show', controller_name: 'enterprise/admin_users/roles' },
      { id: 11, action_name: 'index', controller_name: 'enterprise/admin_users/names' },

    # 审计
      { id: 1001, action_name: 'index', controller_name: 'enterprise', is_nav_link: true },
      { id: 1002, action_name: 'log', controller_name: 'nav' },
      { id: 1003, action_name: 'admin_log_index', controller_name: 'enterprise/admin_log_management', is_nav_link: true },
      { id: 1004, action_name: 'admin_log_index_export', controller_name: 'enterprise/admin_log_management' },
      { id: 1005, action_name: 'index', controller_name: 'enterprise/export_logs' },
      { id: 1006, action_name: 'index', controller_name: 'enterprise/sys_logs' },
      { id: 1007, action_name: 'get_admins', controller_name: 'enterprise/admin_log_management' },
      { id: 1008, action_name: 'association_list', controller_name: 'enterprise/admin_log_management' },

    # 应用审计
    { id: 2522, action_name: 'audits', controller_name: 'nav' },
    { id: 12007, action_name: 'index', controller_name: 'enterprise/app_audits', is_nav_link: true },
    { id: 12008, action_name: 'detail', controller_name: 'enterprise/app_audits' },

    # 应用流量统计
    { id: 12009, action_name: 'index', controller_name: 'enterprise/app_network_traffics', is_nav_link: true },
    { id: 12010, action_name: 'get_filter', controller_name: 'enterprise/app_network_traffics'},
    

    # 应用崩溃统计
    { id: 12019, action_name: 'index', controller_name: 'enterprise/app_crash_stats', is_nav_link: true },
    { id: 12020, action_name: 'get_filter', controller_name: 'enterprise/app_crash_stats'},

    # 系统
      { id: 2001, action_name: 'menu', controller_name: 'top' },
      { id: 2002, action_name: 'about', controller_name: 'top' },
      { id: 2003, action_name: 'license', controller_name: 'top' },
      { id: 2004, action_name: 'cope_stats', controller_name: 'enterprise/stat_charts' },
      { id: 2005, action_name: 'index', controller_name: 'enterprise', is_nav_link: true },

      { id: 2006, action_name: 'terminal', controller_name: 'nav' },
      { id: 2007, action_name: 'index', controller_name: 'enterprise/devices', is_nav_link: true },
      { id: 2008, action_name: 'index', controller_name: 'enterprise/access_templates', is_nav_link: true },
      { id: 2009, action_name: 'index', controller_name: 'enterprise/device_tag_management', is_nav_link: true },
      { id: 2010, action_name: 'index', controller_name: 'enterprise/device_locations', is_nav_link: true },
      { id: 2011, action_name: 'index', controller_name: 'enterprise/attributes', is_nav_link: true },

      { id: 2012, action_name: 'user', controller_name: 'nav' },
      { id: 2013, action_name: 'index', controller_name: 'enterprise/users', is_nav_link: true },

      { id: 2014, action_name: 'app', controller_name: 'nav' },
      { id: 2015, action_name: 'index', controller_name: 'enterprise/apps', is_nav_link: true },
      { id: 2016, action_name: 'index_ios', controller_name: 'enterprise/apps', is_nav_link: true },
      { id: 2017, action_name: 'index', controller_name: 'enterprise/h5s', is_nav_link: true },
      { id: 2018, action_name: 'report_by_app', controller_name: 'enterprise/apps', is_nav_link: true },
      { id: 2019, action_name: 'index', controller_name: 'enterprise/app_access_controls', is_nav_link: true },
      { id: 2020, action_name: 'index', controller_name: 'enterprise/app_policies', is_nav_link: true },

      { id: 2021, action_name: 'security_policy', controller_name: 'nav' },
      { id: 2022, action_name: 'fc_policy_templates', controller_name: 'enterprise/policy_templates', is_nav_link: true },
      { id: 2023, action_name: 'ts_policy_templates', controller_name: 'enterprise/policy_templates', is_nav_link: true },
      { id: 2024, action_name: 'violation_policy_templates', controller_name: 'enterprise/policy_templates', is_nav_link: true },
      { id: 2025, action_name: 'browser_policy_templates', controller_name: 'enterprise/policy_templates', is_nav_link: true },

      { id: 2026, action_name: 'terminal_config', controller_name: 'nav' },
      { id: 2027, action_name: 'wifi_index', controller_name: 'enterprise/policy_configs', is_nav_link: true },
      { id: 2028, action_name: 'smail_index', controller_name: 'enterprise/policy_configs', is_nav_link: true },
      { id: 2029, action_name: 'index', controller_name: 'enterprise/certificate', is_nav_link: true },
      { id: 2030, action_name: 'index', controller_name: 'enterprise/system_vpns', is_nav_link: true },
      { id: 2031, action_name: 'index', controller_name: 'enterprise/contacts', is_nav_link: true },
      { id: 2032, action_name: 'index', controller_name: 'enterprise/system_apns', is_nav_link: true },
      { id: 2033, action_name: 'index', controller_name: 'enterprise/app_access_controls', is_nav_link: true },

      { id: 2034, action_name: 'viri', controller_name: 'nav' },
      { id: 2035, action_name: 'device_index', controller_name: 'enterprise/viri', is_nav_link: true },
      { id: 2036, action_name: 'index', controller_name: 'enterprise/viri', is_nav_link: true },
      { id: 2037, action_name: 'index', controller_name: 'enterprise/virus_library', is_nav_link: true },

      { id: 2038, action_name: 'report', controller_name: 'nav' },
      { id: 2039, action_name: 'index', controller_name: 'enterprise/reports/templates', is_nav_link: true },
      { id: 2040, action_name: 'index', controller_name: 'enterprise/reports/subscriptions', is_nav_link: true },

      { id: 2041, action_name: 'log', controller_name: 'nav' },
      { id: 2042, action_name: 'index_log', controller_name: 'enterprise/report_logs', is_nav_link: true },
      { id: 2043, action_name: 'app_log_index', controller_name: 'enterprise/report_logs', is_nav_link: true },
      { id: 2045, action_name: 'index', controller_name: 'enterprise/export_logs', is_nav_link: true },
      { id: 2046, action_name: 'workspace_log_index', controller_name: 'enterprise/workspace_logs', is_nav_link: true },
      { id: 2048, action_name: 'index', controller_name: 'enterprise/screenshots', is_nav_link: true },

      { id: 2049, action_name: 'system_management', controller_name: 'nav' },
      { id: 2050, action_name: 'index', controller_name: 'enterprise/pubdep', is_nav_link: true },
      { id: 2051, action_name: 'show', controller_name: 'enterprise/client_interface_settings', is_nav_link: true },
      { id: 2052, action_name: 'index', controller_name: 'enterprise/operate_manage', is_nav_link: true },
      { id: 2053, action_name: 'index', controller_name: 'enterprise/agent', is_nav_link: true },
      { id: 2054, action_name: 'index', controller_name: 'enterprise/watermark/parse', is_nav_link: true },
      { id: 2055, action_name: 'show', controller_name: 'enterprise/mng_ctrls', is_nav_link: true },
      { id: 2056, action_name: 'render_global_setting_json', controller_name: 'enterprise/global_settings' },
      { id: 2057, action_name: 'index', controller_name: 'enterprise/admin_users', is_nav_link: true },

      # 查看终端管理
      { id: 2058, action_name: 'operate', controller_name: 'enterprise_devices_action_button' },
      { id: 2059, action_name: 'lock_device', controller_name: 'enterprise/devices' },
      { id: 2060, action_name: 'unlock_device', controller_name: 'enterprise/devices' },
      { id: 2061, action_name: 'set_device_eliminate', controller_name: 'enterprise/devices' },
      { id: 2062, action_name: 'generate_dynamic_code', controller_name: 'enterprise/devices' },
      { id: 2063, action_name: 'reboot_device', controller_name: 'enterprise/devices' },
      { id: 2064, action_name: 'shutdown_device', controller_name: 'enterprise/devices' },
      { id: 2065, action_name: 'wipe_all_data', controller_name: 'enterprise/devices' },
      { id: 2066, action_name: 'wipe_device', controller_name: 'enterprise/devices' },
      { id: 2067, action_name: 'start_ring_alarm', controller_name: 'enterprise/devices' },
      { id: 2068, action_name: 'stop_ring_alarm', controller_name: 'enterprise/devices' },
      { id: 2069, action_name: 'save_label_association', controller_name: 'enterprise/devices' },
      { id: 2070, action_name: 'batch_set_ownership_personal', controller_name: 'enterprise/devices' },
      { id: 2071, action_name: 'batch_set_ownership_corp', controller_name: 'enterprise/devices' },
      { id: 2072, action_name: 'set_device_lost', controller_name: 'enterprise/devices' },
      { id: 2073, action_name: 'set_device_find', controller_name: 'enterprise/devices' },
      { id: 2074, action_name: 'lock_screen', controller_name: 'enterprise/devices' },
      { id: 2075, action_name: 'unlock_screen', controller_name: 'enterprise/devices' },
      { id: 2076, action_name: 'force_change_password', controller_name: 'enterprise/devices' },
      { id: 2077, action_name: 'clear_workspace_passwd', controller_name: 'enterprise/devices' },
      { id: 2078, action_name: 'update_client', controller_name: 'enterprise/devices' },
      { id: 2079, action_name: 'report_state', controller_name: 'enterprise/devices' },
      { id: 2080, action_name: 'show', controller_name: 'enterprise/devices' },
      { id: 2081, action_name: 'push_certificate', controller_name: 'enterprise/devices' },
      { id: 2083, action_name: 'delete', controller_name: 'enterprise/devices' },
      { id: 2084, action_name: 'custom_column', controller_name: 'enterprise/devices' },
      { id: 2085, action_name: 'index_export', controller_name: 'enterprise/devices' },

      # 查看终端准入
      { id: 2086, action_name: 'save_access_template', controller_name: 'enterprise/access_templates' },

      # 查看终端标签
      { id: 2087, action_name: 'create_label_config', controller_name: 'enterprise/label_configs' },
      { id: 2088, action_name: 'create_filter', controller_name: 'enterprise/label_configs' },
      { id: 2089, action_name: 'index_export', controller_name: 'enterprise/device_tag_management' },
      { id: 2090, action_name: 'save_label_config', controller_name: 'enterprise/label_configs' },
      { id: 2091, action_name: 'delete_label_config', controller_name: 'enterprise/label_configs' },

      # 查看自定义属性
      { id: 2092, action_name: 'create_attribute', controller_name: 'enterprise/attributes' },
      { id: 2093, action_name: 'save_attribute', controller_name: 'enterprise/attributes' },
      { id: 2094, action_name: 'delete_attribute', controller_name: 'enterprise/attributes' },
      { id: 2095, action_name: 'index_export', controller_name: 'enterprise/attributes' },

      # enterprise/devices show 页面包含 2080
      { id: 2096, action_name: 'get_client_certificate_info', controller_name: 'enterprise/devices' },
      { id: 2097, action_name: 'get_contact_info', controller_name: 'enterprise/devices' },
      { id: 2098, action_name: 'get_vpn_info', controller_name: 'enterprise/devices' },
      { id: 2099, action_name: 'get_device_location', controller_name: 'enterprise/devices' },
      { id: 2100, action_name: 'policy_templates_info', controller_name: 'enterprise/devices' },
      { id: 2101, action_name: 'save_device_attribute', controller_name: 'enterprise/devices' },

      # 'enterprise/access_templates', :save_access_template 页面包含 2086
      { id: 2102, action_name: 'create_access_template', controller_name: 'enterprise/access_templates' },
      { id: 2103, action_name: 'delete_access_template', controller_name: 'enterprise/access_templates' },

      # 'enterprise/access_templates', :index 页面包含 2008
      { id: 2104, action_name: 'edit_access_template', controller_name: 'enterprise/access_templates' },
      { id: 2105, action_name: 'access_device_details', controller_name: 'enterprise/access_templates' },
      { id: 2106, action_name: 'access_template_config_condition', controller_name: 'enterprise/access_templates' },

      # enterprise/attributes' :index 页面包含 2011
      { id: 2107, action_name: 'attribute_device_list', controller_name: 'enterprise/attributes' },

      # enterprise/rule_templates index 2
      { id: 2108, action_name: 'index', controller_name: 'enterprise/rule_templates/names' },

      #  enterprise/devices show 2080
      { id: 2109, action_name: 'dynamic_update_detail', controller_name: 'enterprise/report' },

      #  enterprise/label_configs, :save_label_config 2090
      { id: 2110, action_name: 'edit_label_config', controller_name: 'enterprise/label_configs' },
      #  'enterprise/device_tag_management', :index 2009
      { id: 2111, action_name: 'label_association_list', controller_name: 'enterprise/label_configs' },

      # 'enterprise/device_locations', :index 2010
      { id: 2112, action_name: 'location_license', controller_name: 'enterprise/device_locations' },

      # 首页 1 1001 2001
      { id: 2113, action_name: 'save_device_attribute', controller_name: 'enterprise/devices' },
      { id: 2114, action_name: 'index', controller_name: 'home' },

      { id: 2115, action_name: 'operate', controller_name: 'enterprise_users_action_button' },
      { id: 2116, action_name: 'add', controller_name: 'enterprise_users_action_button' },
      # 2097
      { id: 2117, action_name: 'check_batch_send_activation_email', controller_name: 'enterprise/users' },
      { id: 2118, action_name: 'activation_email_content', controller_name: 'enterprise/users' },
      { id: 2119, action_name: 'batch_send_activation_email', controller_name: 'enterprise/users' },
      # 2098
      { id: 2120, action_name: 'get_users_phone_info', controller_name: 'enterprise/users' },
      { id: 2121, action_name: 'send_sms', controller_name: 'enterprise/users' },
      # 2099
      { id: 2122, action_name: 'batch_lock', controller_name: 'enterprise/users' },
      # 2100
      { id: 2123, action_name: 'batch_active', controller_name: 'enterprise/users' },
      # 2101
      { id: 2124, action_name: 'initial_password', controller_name: 'enterprise/global_settings' },
      { id: 2125, action_name: 'reset_password', controller_name: 'enterprise/users' },
      # 2102
      { id: 2126, action_name: 'get_change_group_count', controller_name: 'enterprise/users' },
      { id: 2127, action_name: 'user_groups_info', controller_name: 'enterprise/user_groups' },
      { id: 2128, action_name: 'batch_set_group', controller_name: 'enterprise/users' },
      # 2103
      { id: 2129, action_name: 'get_delete_count', controller_name: 'enterprise/users' },
      { id: 2130, action_name: 'batch_delete', controller_name: 'enterprise/users' },
      # 2104
      { id: 2131, action_name: 'get_max_active_devices', controller_name: 'enterprise/users' },
      { id: 2132, action_name: 'batch_set_max_active_devices', controller_name: 'enterprise/users' },
      # 2105
      { id: 2133, action_name: 'refresh_activation_code', controller_name: 'enterprise/users' },
      # 2106
      { id: 2134, action_name: 'os_system_identify_by_user', controller_name: 'enterprise/users' },
      { id: 2135, action_name: 'push_message', controller_name: 'enterprise/users' },
      # 2107
      { id: 2136, action_name: 'push_media_message_check_by_user', controller_name: 'enterprise/users' },
      { id: 2137, action_name: 'push_media', controller_name: 'enterprise/users' },
      # 2109
      { id: 2138, action_name: 'user_groups_info', controller_name: 'enterprise/user_groups' },
      { id: 2139, action_name: 'get_default_group', controller_name: 'enterprise/users' },
      { id: 2140, action_name: 'create', controller_name: 'enterprise/users' },
      # 2110
      { id: 2141, action_name: 'file_to_database', controller_name: 'enterprise/users' },
      { id: 2142, action_name: 'export_user_error_record', controller_name: 'enterprise/users' },
      # 2111
      { id: 2143, action_name: 'get_ldap_config', controller_name: 'enterprise/ldap' },
      { id: 2144, action_name: 'test', controller_name: 'enterprise/ldap' },
      { id: 2145, action_name: 'save', controller_name: 'enterprise/ldap' },
      { id: 2146, action_name: 'index_export', controller_name: 'enterprise/users' },
      # 2113
      { id: 2147, action_name: 'show', controller_name: 'enterprise/users' },
      { id: 2148, action_name: 'user_groups_info', controller_name: 'enterprise/user_groups' },
      { id: 2149, action_name: 'user_detail_update', controller_name: 'enterprise/users' },
      { id: 2150, action_name: 'custom_column', controller_name: 'enterprise/users' },
      { id: 2151, action_name: 'user_groups_info', controller_name: 'enterprise/user_groups' },
      { id: 2152, action_name: 'get_users_by_roll', controller_name: 'enterprise/users' },
      { id: 2153, action_name: 'create', controller_name: 'enterprise/user_groups' },
      { id: 2154, action_name: 'get_group_delete_count', controller_name: 'enterprise/user_groups' },
      { id: 2155, action_name: 'ldap_destory', controller_name: 'enterprise/user_groups' },
      { id: 2156, action_name: 'destroy', controller_name: 'enterprise/user_groups' },
      { id: 2157, action_name: 'set_name', controller_name: 'enterprise/user_groups' },
      { id: 2158, action_name: 'user_detail', controller_name: 'enterprise/users' },
      { id: 2159, action_name: 'user_device_info', controller_name: 'enterprise/users' },

      { id: 2160, action_name: 'index', controller_name: 'enterprise/app_classifications' },
      { id: 2161, action_name: 'push_app', controller_name: 'enterprise/devices' },
      { id: 2162, action_name: 'batch_delete', controller_name: 'enterprise/apps' },
      { id: 2163, action_name: 'batch_download', controller_name: 'enterprise/apps' },
      { id: 2164, action_name: 'clear_third_app_data', controller_name: 'enterprise/devices' },
      { id: 2165, action_name: 'os_system_identify', controller_name: 'enterprise/devices' },
      { id: 2166, action_name: 'push_message', controller_name: 'enterprise/devices' },
      { id: 2167, action_name: 'index_export', controller_name: 'enterprise/apps/android_view' },
      { id: 2168, action_name: 'index', controller_name: 'enterprise/rule_templates/groups' },
      { id: 2169, action_name: 'app_down_groups', controller_name: 'enterprise/apps' },
      { id: 2170, action_name: 'get_app_stats', controller_name: 'enterprise/apps' },
      { id: 2171, action_name: 'wrap_detail', controller_name: 'enterprise/apps' },
      { id: 2172, action_name: 'rewrap', controller_name: 'enterprise/apps' },
      { id: 2173, action_name: 'app_update_info', controller_name: 'enterprise/apps' },
      { id: 2174, action_name: 'index', controller_name: 'rules' },
      { id: 2175, action_name: 'create', controller_name: 'enterprise/h5s' },
      { id: 2176, action_name: 'create', controller_name: 'enterprise/h5s/delete_batch' },
      { id: 2177, action_name: 'clear_third_app_data', controller_name: 'enterprise/devices' },
      { id: 2178, action_name: 'update', controller_name: 'enterprise/h5s' },
      { id: 2179, action_name: 'edit', controller_name: 'enterprise/h5s' },
      { id: 2180, action_name: 'index_export', controller_name: 'enterprise/h5s' },
      { id: 2181, action_name: 'index_ios_export', controller_name: 'enterprise/apps/ios_view' },
      { id: 2182, action_name: 'push_app', controller_name: 'enterprise/apps/android_view' },
      { id: 2183, action_name: 'batch_delete', controller_name: 'enterprise/apps/android_view' },
      { id: 2184, action_name: 'batch_download', controller_name: 'enterprise/apps/android_view' },
      { id: 2185, action_name: 'clear_third_app_data', controller_name: 'enterprise/devices/android_view' },
      { id: 2186, action_name: 'retry', controller_name: 'enterprise/apps/android_view' },
      { id: 2187, action_name: 'edit', controller_name: 'enterprise/apps/android_view' },
      { id: 2188, action_name: 'upgrade', controller_name: 'enterprise/apps/android_view' },
      { id: 2189, action_name: 'get_app_stats', controller_name: 'enterprise/apps/android_view' },
      { id: 2190, action_name: 'wrap_detail', controller_name: 'enterprise/apps/android_view' },
      { id: 2191, action_name: 'rewrap', controller_name: 'enterprise/apps/android_view' },
      { id: 2192, action_name: 'push_app', controller_name: 'enterprise/apps/ios_view' },
      { id: 2193, action_name: 'batch_delete', controller_name: 'enterprise/apps/ios_view' },
      { id: 2194, action_name: 'batch_download', controller_name: 'enterprise/apps/ios_view' },
      { id: 2195, action_name: 'clear_third_app_data', controller_name: 'enterprise/devices/ios_view' },
      { id: 2196, action_name: 'retry', controller_name: 'enterprise/apps/ios_view' },
      { id: 2197, action_name: 'edit', controller_name: 'enterprise/apps/ios_view' },
      { id: 2198, action_name: 'upgrade', controller_name: 'enterprise/apps/ios_view' },
      { id: 2199, action_name: 'wrap_detail', controller_name: 'enterprise/apps/ios_view' },
      { id: 2200, action_name: 'rewrap', controller_name: 'enterprise/apps/ios_view' },
      { id: 2201, action_name: 'retry', controller_name: 'enterprise/apps' },
      { id: 2202, action_name: 'status_by_app', controller_name: 'enterprise/apps' },
      { id: 2203, action_name: 'report_by_app_export', controller_name: 'enterprise/apps' },
      { id: 2204, action_name: 'push_uninstall_task_by_app', controller_name: 'enterprise/devices' },
      { id: 2205, action_name: 'app_policy_items', controller_name: 'enterprise/app_policies' },
      { id: 2206, action_name: 'create', controller_name: 'enterprise/app_policies' },
      { id: 2207, action_name: 'destroy', controller_name: 'enterprise/app_policies' },
      { id: 2208, action_name: 'update', controller_name: 'enterprise/app_policies' },
      { id: 2209, action_name: 'show', controller_name: 'enterprise/app_policies' },
      { id: 2210, action_name: 'create', controller_name: 'enterprise/app_access_controls' },
      { id: 2211, action_name: 'destroys', controller_name: 'enterprise/app_access_controls' },
      { id: 2212, action_name: 'destroy', controller_name: 'enterprise/app_access_controls' },
      { id: 2213, action_name: 'edit', controller_name: 'enterprise/app_access_controls' },
      { id: 2214, action_name: 'update', controller_name: 'enterprise/app_access_controls' },
      { id: 2215, action_name: 'index_export', controller_name: 'enterprise/app_access_controls' },

      { id: 2217, action_name: 'policy_template_json_struction', controller_name: 'enterprise/policy_templates' },
      { id: 2218, action_name: 'get_default_values', controller_name: 'enterprise/policy_templates' },
      { id: 2219, action_name: 'policy_down_groups', controller_name: 'enterprise/policy_templates' },
      { id: 2220, action_name: 'set_policy_template', controller_name: 'enterprise/user_groups' },
      { id: 2221, action_name: 'policy_template_exist', controller_name: 'enterprise/user_groups' },
      { id: 2222, action_name: 'create', controller_name: 'enterprise/policy_templates' },
      { id: 2223, action_name: 'batch_destroy', controller_name: 'enterprise/policy_templates' },
      { id: 2224, action_name: 'index_export', controller_name: 'enterprise/policy_templates' },
      { id: 2225, action_name: 'update', controller_name: 'enterprise/policy_templates' },
      { id: 2226, action_name: 'show', controller_name: 'enterprise/policy_templates' },
      { id: 2227, action_name: 'policy_down_groups', controller_name: 'enterprise/policy_templates' },
      { id: 2228, action_name: 'destroy', controller_name: 'enterprise/policy_templates' },

      { id: 2229, action_name: 'create', controller_name: 'enterprise/policy_templates/fc_policy_templates_view' },
      { id: 2230, action_name: 'update', controller_name: 'enterprise/policy_templates/fc_policy_templates_view' },
      { id: 2231, action_name: 'destroy', controller_name: 'enterprise/policy_templates/fc_policy_templates_view' },
      { id: 2232, action_name: 'fc_policy_templates_export', controller_name: 'enterprise/policy_templates' },

      { id: 2233, action_name: 'create', controller_name: 'enterprise/policy_templates/ts_policy_templates_view' },
      { id: 2234, action_name: 'update', controller_name: 'enterprise/policy_templates/ts_policy_templates_view' },
      { id: 2235, action_name: 'destroy', controller_name: 'enterprise/policy_templates/ts_policy_templates_view' },
      { id: 2236, action_name: 'ts_policy_templates_export', controller_name: 'enterprise/policy_templates' },

      { id: 2237, action_name: 'create', controller_name: 'enterprise/policy_templates/violation_policy_templates_view' },
      { id: 2238, action_name: 'update', controller_name: 'enterprise/policy_templates/violation_policy_templates_view' },
      { id: 2239, action_name: 'destroy', controller_name: 'enterprise/policy_templates/violation_policy_templates_view' },
      { id: 2240, action_name: 'violation_policy_templates_export', controller_name: 'enterprise/policy_templates' },

      { id: 2241, action_name: 'create', controller_name: 'enterprise/policy_templates/browser_policy_templates_view' },
      { id: 2242, action_name: 'update', controller_name: 'enterprise/policy_templates/browser_policy_templates_view' },
      { id: 2243, action_name: 'destroy', controller_name: 'enterprise/policy_templates/browser_policy_templates_view' },
      { id: 2244, action_name: 'browser_policy_templates_export', controller_name: 'enterprise/policy_templates' },

      { id: 2245, action_name: 'create_policy_config', controller_name: 'enterprise/policy_configs' },
      { id: 2246, action_name: 'edit_policy_config', controller_name: 'enterprise/policy_configs' },
      { id: 2247, action_name: 'delete_policy_config', controller_name: 'enterprise/policy_configs' },
      { id: 2248, action_name: 'save_policy_config', controller_name: 'enterprise/policy_configs' },

      { id: 2249, action_name: 'create', controller_name: 'enterprise/policy_configs/wifi_view' },
      { id: 2250, action_name: 'update', controller_name: 'enterprise/policy_configs/wifi_view' },
      { id: 2251, action_name: 'destroy', controller_name: 'enterprise/policy_configs/wifi_view' },
      { id: 2252, action_name: 'wifi_index_export', controller_name: 'enterprise/policy_configs' },

      { id: 2253, action_name: 'create', controller_name: 'enterprise/policy_configs/smail_view' },
      { id: 2254, action_name: 'update', controller_name: 'enterprise/policy_configs/smail_view' },
      { id: 2255, action_name: 'destroy', controller_name: 'enterprise/policy_configs/smail_view' },
      { id: 2256, action_name: 'smail_index_export', controller_name: 'enterprise/policy_configs' },

      { id: 2257, action_name: 'index_export', controller_name: 'enterprise/certificate' },
      { id: 2258, action_name: 'create', controller_name: 'enterprise/certificate' },
      { id: 2259, action_name: 'destroy', controller_name: 'enterprise/certificate' },
      { id: 2260, action_name: 'detail', controller_name: 'enterprise/certificate' },
      { id: 2261, action_name: 'download', controller_name: 'enterprise/certificate' },

      { id: 2262, action_name: 'index_export', controller_name: 'enterprise/system_vpns' },
      { id: 2263, action_name: 'create_vpn', controller_name: 'enterprise/system_vpns' },
      { id: 2264, action_name: 'delete_vpn', controller_name: 'enterprise/system_vpns' },
      { id: 2265, action_name: 'save_vpn', controller_name: 'enterprise/system_vpns' },
      { id: 2266, action_name: 'edit_vpn', controller_name: 'enterprise/system_vpns' },

      { id: 2267, action_name: 'batch_download', controller_name: 'enterprise/contacts' },
      { id: 2268, action_name: 'edit_contact', controller_name: 'enterprise/contacts' },
      { id: 2269, action_name: 'save_contact', controller_name: 'enterprise/contacts' },
      { id: 2270, action_name: 'batch_delete', controller_name: 'enterprise/contacts' },
      { id: 2271, action_name: 'create_button', controller_name: 'enterprise/contacts' },
      { id: 2272, action_name: 'update_button', controller_name: 'enterprise/contacts' },
      { id: 2273, action_name: 'refresh_button', controller_name: 'enterprise/contacts' },
      { id: 2274, action_name: 'index_export', controller_name: 'enterprise/contacts' },
      { id: 2275, action_name: 'create', controller_name: 'enterprise/system_apns' },
      { id: 2276, action_name: 'edit', controller_name: 'enterprise/system_apns' },
      { id: 2277, action_name: 'update', controller_name: 'enterprise/system_apns' },
      { id: 2278, action_name: 'destroys', controller_name: 'enterprise/system_apns' },
      { id: 2279, action_name: 'destroy', controller_name: 'enterprise/system_apns' },
      { id: 2280, action_name: 'index_export', controller_name: 'enterprise/system_apns' },

      { id: 2281, action_name: 'operate', controller_name: 'enterprise_devices_virus_button' },
      { id: 2282, action_name: 'check_virus_operate_status', controller_name: 'enterprise/devices' },
      { id: 2283, action_name: 'fast_scan', controller_name: 'enterprise/devices' },
      { id: 2284, action_name: 'check_virus_operate_status', controller_name: 'enterprise/devices' },
      { id: 2285, action_name: 'full_scan', controller_name: 'enterprise/devices' },
      { id: 2286, action_name: 'check_virus_operate_status', controller_name: 'enterprise/devices' },
      { id: 2287, action_name: 'update_virus_db', controller_name: 'enterprise/devices' },
      { id: 2288, action_name: 'device_index_export', controller_name: 'enterprise/viri' },
      { id: 2289, action_name: 'index_export', controller_name: 'enterprise/viri' },
      { id: 2290, action_name: 'save_config', controller_name: 'enterprise/virus_library' },
      { id: 2291, action_name: 'create', controller_name: 'enterprise/reports/templates' },
      { id: 2292, action_name: 'update', controller_name: 'enterprise/reports/templates' },
      { id: 2293, action_name: 'edit', controller_name: 'enterprise/reports/templates' },
      { id: 2294, action_name: 'destroy', controller_name: 'enterprise/reports/templates' },
      { id: 2295, action_name: 'index_export', controller_name: 'enterprise/reports/templates' },
      { id: 2296, action_name: 'new', controller_name: 'enterprise/reports/subscriptions' },
      { id: 2297, action_name: 'create', controller_name: 'enterprise/reports/subscriptions' },
      { id: 2298, action_name: 'update', controller_name: 'enterprise/reports/subscriptions' },
      { id: 2299, action_name: 'edit', controller_name: 'enterprise/reports/subscriptions' },
      { id: 2300, action_name: 'destroy', controller_name: 'enterprise/reports/subscriptions' },
      { id: 2301, action_name: 'index_export', controller_name: 'enterprise/reports/subscriptions' },
      { id: 2302, action_name: 'index_log_export', controller_name: 'enterprise/report_logs' },
      { id: 2303, action_name: 'app_log_index_export', controller_name: 'enterprise/report_logs' },
      { id: 2304, action_name: 'workspace_log_index_export', controller_name: 'enterprise/workspace_logs' },
      { id: 2305, action_name: 'download', controller_name: 'enterprise/export_logs' },
      { id: 2306, action_name: 'destroy', controller_name: 'enterprise/export_logs' },
      { id: 2307, action_name: 'speed_up', controller_name: 'enterprise/export_logs' },

      { id: 2308, action_name: 'create_update', controller_name: 'qihu/upgrades' },
      { id: 2309, action_name: 'detail', controller_name: 'qihu/upgrades' },
      { id: 2310, action_name: 'update', controller_name: 'qihu/upgrades' },
      { id: 2311, action_name: 'qrcode', controller_name: 'qihu/upgrades' },
      { id: 2312, action_name: 'destroy', controller_name: 'qihu/upgrades' },
      { id: 2313, action_name: 'records', controller_name: 'qihu/upgrades' },

      { id: 2314, action_name: 'android_tab', controller_name: 'qihu/upgrades/android_tab_view' },
      { id: 2316, action_name: 'create', controller_name: 'qihu/upgrades/android_tab_view' },
      { id: 2317, action_name: 'update', controller_name: 'qihu/upgrades/android_tab_view' },
      { id: 2318, action_name: 'destroy', controller_name: 'qihu/upgrades/android_tab_view' },
      { id: 2319, action_name: 'qrcode', controller_name: 'qihu/upgrades/android_tab_view' },

      { id: 2320, action_name: 'ios_tab', controller_name: 'qihu/upgrades/ios_tab_view' },
      { id: 2321, action_name: 'create', controller_name: 'qihu/upgrades/ios_tab_view' },
      { id: 2322, action_name: 'update', controller_name: 'qihu/upgrades/ios_tab_view' },
      { id: 2323, action_name: 'destroy', controller_name: 'qihu/upgrades/ios_tab_view' },
      { id: 2324, action_name: 'qrcode', controller_name: 'qihu/upgrades/ios_tab_view' },

      { id: 2325, action_name: 'create', controller_name: 'enterprise/client_interface_settings' },
      { id: 2326, action_name: 'upload', controller_name: 'enterprise/client_interface_settings' },

      # 系统备份
      { id: 2327, action_name: 'backup_tab', controller_name: 'enterprise/operate_manage' },
      { id: 2328, action_name: 'auto_check_method', controller_name: 'enterprise/operate_manage' },
      { id: 2329, action_name: 'global_show_status', controller_name: 'enterprise/operate_manage' },
      { id: 2330, action_name: 'manual_backup', controller_name: 'enterprise/operate_manage' },
      { id: 2331, action_name: 'manual_download', controller_name: 'enterprise/operate_manage' },

      # 系统还原
      { id: 2332, action_name: 'reset_tab', controller_name: 'enterprise/operate_manage' },
      { id: 2333, action_name: 'restore_system', controller_name: 'enterprise/operate_manage' },

      # 系统升级
      { id: 2334, action_name: 'upgrade_tab', controller_name: 'enterprise/operate_manage' },
      { id: 2335, action_name: 'get_update_version', controller_name: 'enterprise/operate_manage' },
      { id: 2336, action_name: 'update_system', controller_name: 'enterprise/operate_manage' },

      # 服务器迁移
      { id: 2337, action_name: 'migration_tab', controller_name: 'enterprise/operate_manage' },
      { id: 2338, action_name: 'tianji_migration_server_config', controller_name: 'enterprise/service_migration' },
      { id: 2339, action_name: 'reset_tianji_migration_server', controller_name: 'enterprise/service_migration' },
      { id: 2340, action_name: 'tianji_migration_server_detail', controller_name: 'enterprise/service_migration' },

      # 系统端口
      { id: 2341, action_name: 'port_tab', controller_name: 'enterprise/operate_manage' },
      { id: 2342, action_name: 'get_port', controller_name: 'enterprise/global_settings' },
      { id: 2343, action_name: 'set_port', controller_name: 'enterprise/global_settings' },

      { id: 2344, action_name: 'create', controller_name: 'enterprise/agent' },
      { id: 2345, action_name: 'batch_download', controller_name: 'enterprise/agent' },
      { id: 2346, action_name: 'destroy', controller_name: 'enterprise/agent' },
      { id: 2347, action_name: 'agent_device_detail', controller_name: 'enterprise/agent' },
      { id: 2348, action_name: 'save_agent', controller_name: 'enterprise/agent' },
      { id: 2349, action_name: 'edit_agent', controller_name: 'enterprise/agent' },
      { id: 2350, action_name: 'index_export', controller_name: 'enterprise/agent' },
      { id: 2351, action_name: 'create', controller_name: 'enterprise/watermark/parse' },
      { id: 2352, action_name: 'update', controller_name: 'enterprise/mng_ctrls' },
      { id: 2353, action_name: 'get_ldap_auth_config', controller_name: 'enterprise/ldap' },
      { id: 2354, action_name: 'index', controller_name: 'enterprise/ios_certificates' },
      { id: 2355, action_name: 'set', controller_name: 'enterprise/global_settings' },

      { id: 2356, action_name: 'create', controller_name: 'enterprise/admin_users' },
      { id: 2357, action_name: 'user_detail', controller_name: 'enterprise/admin_users' },
      { id: 2358, action_name: 'user_detail_update', controller_name: 'enterprise/admin_users' },
      { id: 2359, action_name: 'batch_delete', controller_name: 'enterprise/admin_users' },
      { id: 2360, action_name: 'index_export', controller_name: 'enterprise/admin_users' },

      { id: 2361, action_name: 'violation_chart', controller_name: 'enterprise/report' },
      { id: 2362, action_name: 'policy_deployment_chart', controller_name: 'enterprise/report' },
      { id: 2363, action_name: 'devices_status', controller_name: 'enterprise/report' },
      { id: 2364, action_name: 'device_security_chart', controller_name: 'enterprise/report' },
      { id: 2365, action_name: 'os_info_chart', controller_name: 'enterprise/report' },
      { id: 2366, action_name: 'ownership_chart', controller_name: 'enterprise/report' },
      { id: 2367, action_name: 'newest_logs', controller_name: 'enterprise/report' },
      { id: 2368, action_name: 'tianji_version_chart', controller_name: 'enterprise/report' },
      { id: 2369, action_name: 'active_devices_chart', controller_name: 'enterprise/report' },
      { id: 2370, action_name: 'platform_overview_chart', controller_name: 'enterprise/report' },
      { id: 2371, action_name: 'get_filter', controller_name: 'enterprise/report_logs' },
      { id: 2372, action_name: 'index', controller_name: 'enterprise/policy_templates' },
      { id: 2373, action_name: 'get_installation_situation', controller_name: 'enterprise/app_policies' },
      { id: 2374, action_name: 'policy_detail_unforced', controller_name: 'enterprise/app_policies' },
      { id: 2375, action_name: 'policy_detail_enforced', controller_name: 'enterprise/app_policies' },
      { id: 2376, action_name: 'get_installation_situation', controller_name: 'enterprise/policy_templates' },
      { id: 2377, action_name: 'policy_detail_unforced', controller_name: 'enterprise/policy_templates' },
      { id: 2378, action_name: 'policy_detail_enforced', controller_name: 'enterprise/policy_templates' },
      { id: 2379, action_name: 'virus_detail', controller_name: 'enterprise/viri' },
      { id: 2380, action_name: 'get_infect_devices', controller_name: 'enterprise/viri' },
      { id: 2381, action_name: 'change_admin_email_password', controller_name: 'enterprise/admin_users' },
      { id: 2382, action_name: 'get_delete_count', controller_name: 'enterprise/admin_users' },
      { id: 2383, action_name: 'change_password', controller_name: 'enterprise/admin_users' },
      { id: 2384, action_name: 'index', controller_name: 'enterprise/wxgzs/mtp' },
      { id: 2385, action_name: 'location_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2386, action_name: 'user_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2387, action_name: 'afk_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2388, action_name: 'risk_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2389, action_name: 'top_app_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2390, action_name: 'risk_detection_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2391, action_name: 'app_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2392, action_name: 'sec_event_stat_chart', controller_name: 'enterprise/stat_charts' },
      { id: 2393, action_name: 'byod_stats', controller_name: 'enterprise/stat_charts' },
      { id: 2394, action_name: 'app_list', controller_name: 'enterprise/stat_charts' },
      { id: 2395, action_name: 'save_app_list', controller_name: 'enterprise/stat_charts' },
      { id: 2396, action_name: 'index', controller_name: 'enterprise/sys_logs' },
      { id: 2397, action_name: 'create_filter', controller_name: 'enterprise/filter' },
      { id: 2398, action_name: 'delete_filter', controller_name: 'enterprise/filter' },
      { id: 2399, action_name: 'edit_filter', controller_name: 'enterprise/filter' },
      { id: 2400, action_name: 'get_pull_down_menu_list', controller_name: 'enterprise/filter' },
      { id: 2401, action_name: 'filter_device_list', controller_name: 'enterprise/filter' },
      { id: 2402, action_name: 'save_filter', controller_name: 'enterprise/filter' },
      { id: 2403, action_name: 'index', controller_name: 'enterprise/app_access_controls' },
      { id: 2404, action_name: 'batch_import_user', controller_name: 'enterprise/users' },
      { id: 2405, action_name: 'get_user', controller_name: 'enterprise/ldap' },
      { id: 2406, action_name: 'operate', controller_name: 'enterprise/user_groups/sidebar' },
      { id: 2407, action_name: 'index', controller_name: 'enterprise/h5s/installations' },
      { id: 2408, action_name: 'index', controller_name: 'enterprise/h5s/installed' },
      { id: 2409, action_name: 'index', controller_name: 'enterprise/h5s/uninstalled' },
      { id: 2410, action_name: 'create', controller_name: 'enterprise/h5s/icons' },
      { id: 2411, action_name: 'destroy', controller_name: 'enterprise/h5s' },
      { id: 2412, action_name: 'ios_index', controller_name: 'enterprise/apps' },
      { id: 2413, action_name: 'upload_virus_library', controller_name: 'enterprise/virus_library' },
      { id: 2414, action_name: 'syn_immediately', controller_name: 'enterprise/virus_library' },

      { id: 2415, action_name: 'upload_logo', controller_name: 'enterprise/global_settings' },
      { id: 2416, action_name: 'upload_ssl', controller_name: 'enterprise/global_settings' },
      { id: 2417, action_name: 'upload_blank', controller_name: 'enterprise/global_settings' },
      { id: 2418, action_name: 'reset_logo', controller_name: 'enterprise/global_settings' },
      { id: 2419, action_name: 'reset_wallpaper', controller_name: 'enterprise/global_settings' },
      { id: 2420, action_name: 'reset_contact', controller_name: 'enterprise/global_settings' },
      { id: 2421, action_name: 'upload_banner', controller_name: 'enterprise/global_settings' },
      { id: 2422, action_name: 'upload_contact_csv', controller_name: 'enterprise/global_settings' },
      { id: 2423, action_name: 'test_sso_config', controller_name: 'enterprise/global_settings' },
      { id: 2424, action_name: 'test_sms_config', controller_name: 'enterprise/global_settings' },
      { id: 2425, action_name: 'test_its_config', controller_name: 'enterprise/global_settings' },
      { id: 2426, action_name: 'restore_default', controller_name: 'enterprise/global_settings' },
      { id: 2427, action_name: 'upload_agent', controller_name: 'enterprise/agent' },
      { id: 2428, action_name: 'workspace_access_details', controller_name: 'enterprise/workspace_logs' },
      { id: 2429, action_name: 'config_detail_enforced', controller_name: 'enterprise/policy_configs' },
      { id: 2430, action_name: 'config_detail_unforced', controller_name: 'enterprise/policy_configs' },
      { id: 2431, action_name: 'app_detail', controller_name: 'enterprise/apps' },
      { id: 2432, action_name: 'get_screen_captures', controller_name: 'enterprise/device_screen_captures' },
      { id: 2433, action_name: 'vpn_detail_enforced', controller_name: 'enterprise/system_vpns' },
      { id: 2434, action_name: 'vpn_detail_unforced', controller_name: 'enterprise/system_vpns' },
      { id: 2435, action_name: 'upload_media', controller_name: 'enterprise/devices' },
      { id: 2436, action_name: 'create_sensitive_word', controller_name: 'enterprise/sensitive_words' },
      { id: 2437, action_name: 'upload_sensitive_word_file', controller_name: 'enterprise/sensitive_words' },
      { id: 2438, action_name: 'save_sensitive_word', controller_name: 'enterprise/sensitive_words' },
      { id: 2439, action_name: 'batch_delete', controller_name: 'enterprise/sensitive_words' },
      { id: 2440, action_name: 'export_sensitive_record', controller_name: 'enterprise/sensitive_words' },
      { id: 2441, action_name: 'index', controller_name: 'enterprise/sensitive_words' },
      { id: 2442, action_name: 'create', controller_name: 'enterprise/sensitive_words' },
      { id: 2443, action_name: 'new', controller_name: 'enterprise/sensitive_words' },
      { id: 2444, action_name: 'edit', controller_name: 'enterprise/sensitive_words' },
      { id: 2445, action_name: 'show', controller_name: 'enterprise/sensitive_words' },
      { id: 2446, action_name: 'update', controller_name: 'enterprise/sensitive_words' },
      { id: 2447, action_name: 'destroy', controller_name: 'enterprise/sensitive_words' },
      { id: 2448, action_name: 'upload_certificate', controller_name: 'enterprise/certificate' },
      { id: 2449, action_name: 'upload_contact_csv', controller_name: 'enterprise/contacts' },
      { id: 2450, action_name: 'vpn_auth_menus', controller_name: 'enterprise/system_vpns' },
      { id: 2451, action_name: 'create', controller_name: 'enterprise/ios_certificates/mdm' },
      { id: 2452, action_name: 'create', controller_name: 'enterprise/ios_certificates/apns' },
      { id: 2453, action_name: 'create', controller_name: 'enterprise/ios_certificates/scep' },
      { id: 2454, action_name: 'create', controller_name: 'enterprise/ios_certificates/scep_key' },
      { id: 2455, action_name: 'update', controller_name: 'enterprise/ios_certificates/mdm/verify' },
      { id: 2456, action_name: 'update', controller_name: 'enterprise/ios_certificates/apns/verify' },
      { id: 2457, action_name: 'update', controller_name: 'enterprise/ios_certificates/scep/verify' },
      { id: 2458, action_name: 'app_detail_install',controller_name: 'enterprise/apps' },
      { id: 2459, action_name: 'app_detail_uninstall',controller_name: 'enterprise/apps' },
      { id: 2460, action_name: 'index',controller_name: 'enterprise/ios_certificates/all_verified' },
      { id: 2461, action_name: 'create',controller_name: 'enterprise/h5s/icons/upload' },
      { id: 2462, action_name: 'item',controller_name: 'nav/ios_apps' },
      { id: 2463, action_name: 'delete_device',controller_name: 'enterprise/devices' },
      { id: 2464, action_name: 'device_statistics',controller_name: 'enterprise/contacts' },
      { id: 2465, action_name: 'contact_details',controller_name: 'enterprise/contacts' },
      { id: 2466, action_name: 'install_detail',controller_name: 'enterprise/certificate' },
      { id: 2467, action_name: 'uninstall_detail',controller_name: 'enterprise/certificate' },
      { id: 2468, action_name: 'show',controller_name: 'enterprise/screenshots' },
      { id: 2469, action_name: 'restore_upload', controller_name: 'enterprise/operate_manage' },
      { id: 2470, action_name: 'update_check', controller_name: 'enterprise/operate_manage' },
      { id: 2471, action_name: 'edit_label_association', controller_name: 'enterprise/devices' },
      { id: 2472, action_name: 'lock_device_identify', controller_name: 'enterprise/devices' },
      { id: 2473, action_name: 'get_report_logs', controller_name: 'enterprise/devices' },
      { id: 2474, action_name: 'device_detail', controller_name: 'enterprise/report' },
      { id: 2475, action_name: 'screen_captures', controller_name: 'enterprise/devices' },
      { id: 2476, action_name: 'device_identify', controller_name: 'enterprise/devices' },
      { id: 2477, action_name: 'create_or_update_classification', controller_name: 'enterprise/app_classifications' },
      { id: 2478, action_name: 'destroy_classification', controller_name: 'enterprise/app_classifications' },
      { id: 2479, action_name: 'encap_policy_templates', controller_name: 'enterprise/policy_templates' },
      { id: 2480, action_name: 'managements', controller_name: 'enterprise/apps' },
      { id: 2481, action_name: 'create_encap_policy_template', controller_name: 'enterprise/policy_templates' },
      { id: 2482, action_name: 'update_encap_policy_template', controller_name: 'enterprise/policy_templates' },
      { id: 2483, action_name: 'edit_encap_policy_template', controller_name: 'enterprise/policy_templates' },
      { id: 2484, action_name: 'ios_managements', controller_name: 'enterprise/apps' },

      { id: 5000, action_name: 'suites', controller_name: 'nav' },


      { id: 2485, action_name: 'vpn_auth_menus', controller_name: 'enterprise/system_vpns' },
      { id: 2486, action_name: 'update_upload', controller_name: 'enterprise/operate_manage' },
      { id: 2487, action_name: 'device_virus_log', controller_name: 'enterprise/viri' },
      { id: 2488, action_name: 'cancel_virus_scan', controller_name: 'enterprise/devices' },
      { id: 2489, action_name: 'cancel_device_selected_status', controller_name: 'enterprise/devices' },
      { id: 2490, action_name: 'report_location', controller_name: 'enterprise/devices' },
      { id: 2491, action_name: 'admin_log_index', controller_name: 'enterprise/admin_log_management' },
      { id: 2492, action_name: 'set_default_values', controller_name: 'enterprise/policy_templates' },
      { id: 2493, action_name: 'push_uninstall_task_by_device', controller_name: 'enterprise/devices' },
      { id: 2494, action_name: 'cancel_virus_db_update', controller_name: 'enterprise/devices' },
      { id: 2495, action_name: 'destroy', controller_name: 'enterprise/ios_certificates/mdm' },
      { id: 2496, action_name: 'destroy', controller_name: 'enterprise/ios_certificates/apns' },
      { id: 2497, action_name: 'destroy', controller_name: 'enterprise/ios_certificates/scep' },
      { id: 2498, action_name: 'create_access_file', controller_name: 'enterprise/access_file' },
      { id: 2499, action_name: 'batch_access_file_recode_status', controller_name: 'enterprise/access_file' },
      { id: 2500, action_name: 'exporting_template', controller_name: 'enterprise/policy_templates' },
      { id: 2501, action_name: 'sensitive_report_log', controller_name: 'enterprise/report_logs' },
      { id: 2502, action_name: 'save_user', controller_name: 'enterprise/ldap' },

      { id: 2503, action_name: 'index', controller_name: 'enterprise/app_areas' },
      { id: 2504, action_name: 'create_or_update_area', controller_name: 'enterprise/app_areas' },
{ id: 2505, action_name: 'destroy_area', controller_name: 'enterprise/app_areas' },
{ id: 2506, action_name: './project-file/init_action_names.rake', controller_name: 'enterprise/./project-file/init_action_names.rake' }
],
    ActionName.delete_all
    ActionName.import action_names.map { |a| ActionName.new(a) }
  end
end
